### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by paqi-cry** [SlopeCraft/SlopeCraft#94]
### Please choose if applies:

- [ ] I'm currently working on adding this feature.

### Describe the solution you'd like

I hope to add the ability to disable a certain color in the next update, because rawIron colors are really too hard to get in survival

### Please accept these terms

- [X] I have searched the [existing issues](https://github.com/SlopeCraft/SlopeCraft/issues) and this has not been posted before

**Comment by paqi-cry** [comment]
Thank you very much, there is a small problem about 5.0.0 and 5.0.1 I can not use the situation, when I click SlopeCraft.exe he will pop up the application can not start properly (0xc0000142), please ask if you have a solution

**Comment by ToKiNoBug** [comment]
> Thank you very much, there is a small problem about 5.0.0 and 5.0.1 I can not use the situation, when I click SlopeCraft.exe he will pop up the application can not start properly (0xc0000142), please ask if you have a solution

I have already worked around this error(#89 , usually this is because your OS or CPU doesn't support AVX2 intrinstic. Running SlopeCraft in vitural machines are not supported because usually they don't support AVX2. 

If virual machines are not the case, tell me the name of your CPU, it may not support AVX2. In this condition, you can download **SlopeCraft-5.x.x-win64-noGPU-noAVX2.7z** instead, this release is built without AVX2 and gpu acceleration to attain best compability.

**Comment by paqi-cry** [comment]
The problem has been solved, thank you very much
